{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFaceTrackingResult"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/facecapture\/facecaptureerror\/invalidfacetrackingresult"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError\/invalidFaceTrackingResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Expression requires a face tracking result with a property that’s unavailable on that particular result"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFaceTrackingResult"}],"title":"FaceCaptureError.invalidFaceTrackingResult","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11FaceCapture0aB5ErrorO07invalidA14TrackingResultyA2CmF","modules":[{"name":"FaceCapture"}]},"hierarchy":{"paths":[["doc:\/\/FaceCapture\/documentation\/FaceCapture","doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError"]]},"references":{"doc://FaceCapture/documentation/FaceCapture":{"role":"collection","title":"FaceCapture","abstract":[{"type":"text","text":"Capture faces using your device’s camera"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture","kind":"symbol","type":"topic","url":"\/documentation\/facecapture"},"doc://FaceCapture/documentation/FaceCapture/FaceCaptureError":{"role":"symbol","title":"FaceCaptureError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceCaptureError"}],"abstract":[{"type":"text","text":"Error thrown by the face capture library"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceCaptureError"}],"url":"\/documentation\/facecapture\/facecaptureerror"},"doc://FaceCapture/documentation/FaceCapture/FaceCaptureError/invalidFaceTrackingResult":{"role":"symbol","title":"FaceCaptureError.invalidFaceTrackingResult","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFaceTrackingResult"}],"abstract":[{"type":"text","text":"Expression requires a face tracking result with a property that’s unavailable on that particular result"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError\/invalidFaceTrackingResult","kind":"symbol","type":"topic","url":"\/documentation\/facecapture\/facecaptureerror\/invalidfacetrackingresult"}}}