{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/facecapture\/facecaptureerror\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError\/description","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"String description of the error"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:11FaceCapture0aB5ErrorO11descriptionSSvp","modules":[{"name":"FaceCapture"}]},"hierarchy":{"paths":[["doc:\/\/FaceCapture\/documentation\/FaceCapture","doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError"]]},"references":{"doc://FaceCapture/documentation/FaceCapture":{"role":"collection","title":"FaceCapture","abstract":[{"type":"text","text":"Capture faces using your deviceâ€™s camera"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture","kind":"symbol","type":"topic","url":"\/documentation\/facecapture"},"doc://FaceCapture/documentation/FaceCapture/FaceCaptureError":{"role":"symbol","title":"FaceCaptureError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceCaptureError"}],"abstract":[{"type":"text","text":"Error thrown by the face capture library"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceCaptureError"}],"url":"\/documentation\/facecapture\/facecaptureerror"},"doc://FaceCapture/documentation/FaceCapture/FaceCaptureError/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"String description of the error"}],"identifier":"doc:\/\/FaceCapture\/documentation\/FaceCapture\/FaceCaptureError\/description","kind":"symbol","type":"topic","url":"\/documentation\/facecapture\/facecaptureerror\/description"}}}